[build]
  base = "omegle1-main/frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "omegle1-main/frontend/build"

[build.environment]
  NODE_VERSION = "20.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

